---

- name: Create a directory for cert manager
  file:
    path: /root/certmanager
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy the files to the directory
  copy:
    dest: /root/certmanager/
    src: files/

- name: Verify if helm is installed on the system
  shell:
    cmd: helm version
  register: helm_check
  failed_when: "'version.BuildInfo' not in helm_check.stdout"
  changed_when: false

- name: Print the helm version
  debug:
    msg: "{{ helm_check.stdout }}"
  when: helm_check.stdout is defined


- name: Install cert manager on the cluster
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: /root/certmanager
    release_state: present
    values_files: "/root/certmanager/values.yaml"
    release_namespace: "cert-manager"
    create_namespace: true

- name: Wait for the probes to be ready
  pause:
    seconds: 30

- name: Create the cluster issuer
  kubernetes.core.k8s:
    src: "/root/certmanager/cluster-issuer.yaml"
    state: present
    kubeconfig: /etc/kubernetes/admin.conf







